import Navbar from "src/Components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "src/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tamasakti Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        {/* <footer className="w-10/12 mx-auto ">
          <Footer />
        </footer> */}
      </body>
    </html>
  );
}
